name: Greetings

on: [pull_request_target, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: "We are SimSimi app this photo tool, you must be where characteristic now. Regards, SimSimi."
        pr-message: "We are feedback now SimSimi in 24 hours pull request."
